travis:
  secure:
    BINSTAR_TOKEN: GdwHPSqFZ6rk0GtBh++TJBxIadmftK+Ee0KD1bojesnLcA/1kihqfYapE+CkDzAysoFaf9nJxPQubF2tr/DBQEgK80+IBRMPGa7QsMg1spJ53MuJs5j2wEqBarWsVZBAP4Evs7Ha5KOdsgNDklyr1LfVDqu711tZS7D7BvKmbZoYpf0XoMBjMjK6JnyQ4sKUaLqWMZ2ut6w6YW1CovsE4Mz5r8pHUa5HKQ/N9cXwaSedlTj+y0630A5MdvOhWuhp1Kb3lVgTThTBje1WqCckhlz3XbXonS4IH8oZHxNwfJEPjmOybFKC1ayz5yb78sLyGLk9ejOcDNtUkbGiVpkh+pSmQPFRd/FHD6VaD6atDxtD5oGGqTP5lsbVYkziK/caqvZMk113Cy8qPz0oOf31ygcgKCh3nJ6NyjBgcmYldg7WqhSSN6GkwHYEE3BrAKKZIpB3Nt2oxHDa69ttHf0sL+LW0XGYjpyBScUhe8Ur+F1FjCMvdBTxVVFAtKhnbx5zzxxPJeJocCgYPKIvxwGwaiEWH8fxHXd69MKfqW8Ia17dMHd6kkrwEhejaxrYfTkkwykemGcWH1HiNzXE/KHZzmtBYlTkOkj4g4K/vzck0HrIUA6TgpqQ0lT7/NScdRekyPOT/1wocdyUaiUwES30po31zE7SF6QNEF3wCsApqis=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
